title: Артем Сысолятин
description: художник по свету, видеоинженер
permalink: /light/:title/
navigation_links:
  - title: главная
    url: /

  - title: приложения
    url: /apps

apps:
  - name: "MIDI to grandMA2"
    url: https://midigma.com
    icon: /static/midigma.svg
    text: "Удобная работа с MIDI контроллерами в пультах grandMA2"

  - name: "Timecode конвертнер"
    url: https://timecode.su
    icon: /static/timecode-su.svg
    text: "Конвертер меток из Reaper в таймкоды разных световых пультов"

  - name: "Cue-лист инфо"
    url: /tools/cue-info/
    icon: /static/cue-info.svg
    text: "Получение печатной информации о CUE-листе из grandMA2"

  - name: "Blinder Tools"
    url: /light/blinders/
    icon: /static/blinder-tools.svg
    text: "grandMA2-плагин для работы с китайскими блайндерами"
  
  - name: "BPM tool"
    url: /bpm
    icon: /static/bpm.svg
    text: "Приложение для подсчета количества ударов в минуту"

  - name: "Position Layout"
    url: /apps/position/
    icon: /static/position.svg
    text: "grandMA2-плагин для работы с позициями приборов в баскинге"

  - name: "DimFX"
    url: /apps/dimfx/
    icon: /static/dimfx.svg
    text: "grandMA2-плагин для создания диммерных эффектов для группы"

  - name: "grandMA Fixture Finder"
    url: https://mafixture.ru
    icon: /static/fixturefind.svg
    text: "Поиск библиотек для световых приборов в пультах grandMA"

  - name: "Test Screen Generator"
    url: /apps/screen-test
    icon: /static/test-screen.png
    text: "Генератор тестовых изображений для светодиодных экранов"

theme: minima
plugins:
  - jekyll-feed